# Welcome to Jekyll!
#

# Site settings
title: Glow3D
description: |
  Glow3D: lightweight, cross-platform compact game engine, created by Iakov Sumygin
owner: yak32 # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: yak32_games@gmail.com
name: Glow3D
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.glow3d.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/yak32
  github: https://github.com/yak32
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/yakov.sum
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-97733057-1

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
